genres = {
    "No Preference":"1.Best_Books_Ever",
    "Art": "2390.Best_Art_and_Art_History_Books",
    "Graphic Novels": "210.Best_Graphic_Novels",
    "Manga": "489",
    "Memoir": "281.Best_Memoir_Biography_Autobiography",
    "Business": "1170.Best_Business_Books",
    "Children's": "86.Best_Children_s_Books",
    "Picture Books": "460.Best_Picture_Books",
    "Humor": "312.Best_Humorous_Books",
    "Fantasy": "88",
    "Epic Fantasy": "50.The_Best_Epic_Fantasy_fiction_",
    "Urban Fantasy": "51.The_Best_Urban_Fantasy",
    "Non-Fiction": "134.Best_Non_Fiction_no_biographies_",
    "YA Realistic Fiction": "1736.Best_Teen_Books_About_Real_Problems",
    "Classics": "2522.Cult_Classics",
    "Historical Fiction": "15.Best_Historical_Fiction",
    "Science Fiction": "19341.Best_Science_Fiction",
    "Gay Fiction": "445.Best_Gay_Fiction",
    "Dystopia": "47.Best_Dystopian_and_Post_Apocalyptic_Fiction",
    "History": "1362.Best_History_Books_",
    "Feminist": "62.Best_Feminist_Books",
    "War": "824.Best_Non_fiction_War_Books",
    "Horror": "135.Best_Horror_Novels",
    "Gothic": "1230.Best_Gothic_Books_Of_All_Time",
    "Vampires": "129.Best_Adult_Vampire_Books",
    "Mystery": "11.Best_Crime_Mystery_Books",
    "Thrillers": "8306.Thrillers_You_Must_Read_",
    "Poetry": "36.Best_Poetry_Books",
    "Christian": "946.Books_Besides_the_Bible_Recommended_for_Christian_Readers",
    "Romance": "12362.All_Time_Favorite_Romance_Novels",
    "Contemporary Romance": "57.Best_Ever_Contemporary_Romance_Books",
    "YA Romance": "1333.Young_Adult_Romance",
    "Paranormal Romance": "397.Best_Paranormal_Romance_Series",
    "Fantasy Romance": "9088.Best_ADULT_Urban_Fantasy_Fantasy_and_Paranormal_Romance",
    "Social Justice": "851.Social_Justice_Books_on_Racism_Sexism_and_Class",
    "Psychology": "1295.Greatest_Psychology_Books",
    "Self Help": "691.Best_Self_Help_Books",
    "Travel": "633.Favorite_Travel_Books",
}
